from django.shortcuts import render
from accounts.models import *
from accounts.serializers import *
from django.http import Http404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status

"""1.create user(Phone_number,Name,Date_of_birth,Gender,Image), Create user cart while creating user(post request)
2.get all users(get request)
3.create a product(Unique id is to be generated by using django signals)(post request)
4.get all products with images(get request)
5.create product with multiple images(post request)
6.send otp with email(post request)
7.Login with otp and email(post request)
8.Add product to cart .(post request)
"""
class UserData(APIView):
    def get(self, request, format=None):
        snippets = User.objects.all()
        serializer = UserSerializer(snippets, many=True)
        return Response(serializer.data)

    def post(self, request, format=None):
        serializer = UserSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
class UserCart(APIView):
     def get(self, request, format=None):
        snippets = CartModel.objects.all()
        serializer = CartModelSerializer(snippets, many=True)
        return Response(serializer.data)
     
     def post(self, request, format=None):
        serializer = CartModel(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    

    

class GetUSerList(APIView):
    def get(self, request, format=None):
        snippets = UserProfile.objects.all()
        serializer = UserProfileSerializer(snippets, many=True)
        return Response(serializer.data)
    
